// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mutationNested
int mutationNested(IntegerVector des, IntegerVector ans);
RcppExport SEXP _CasPhy_mutationNested(SEXP desSEXP, SEXP ansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type des(desSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ans(ansSEXP);
    rcpp_result_gen = Rcpp::wrap(mutationNested(des, ans));
    return rcpp_result_gen;
END_RCPP
}
// mutationNestedBit
int mutationNestedBit(IntegerVector des, IntegerVector ans);
RcppExport SEXP _CasPhy_mutationNestedBit(SEXP desSEXP, SEXP ansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type des(desSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ans(ansSEXP);
    rcpp_result_gen = Rcpp::wrap(mutationNestedBit(des, ans));
    return rcpp_result_gen;
END_RCPP
}
// transitionRoot
int transitionRoot(IntegerVector transition, int idx);
RcppExport SEXP _CasPhy_transitionRoot(SEXP transitionSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type transition(transitionSEXP);
    Rcpp::traits::input_parameter< int >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(transitionRoot(transition, idx));
    return rcpp_result_gen;
END_RCPP
}
// matCoding
IntegerVector matCoding(IntegerMatrix mat, IntegerVector loci);
RcppExport SEXP _CasPhy_matCoding(SEXP matSEXP, SEXP lociSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type loci(lociSEXP);
    rcpp_result_gen = Rcpp::wrap(matCoding(mat, loci));
    return rcpp_result_gen;
END_RCPP
}
// int2binary
LogicalVector int2binary(IntegerVector ve, int output_len);
RcppExport SEXP _CasPhy_int2binary(SEXP veSEXP, SEXP output_lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ve(veSEXP);
    Rcpp::traits::input_parameter< int >::type output_len(output_lenSEXP);
    rcpp_result_gen = Rcpp::wrap(int2binary(ve, output_len));
    return rcpp_result_gen;
END_RCPP
}
// int2idx
std::vector<int> int2idx(IntegerVector ve);
RcppExport SEXP _CasPhy_int2idx(SEXP veSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ve(veSEXP);
    rcpp_result_gen = Rcpp::wrap(int2idx(ve));
    return rcpp_result_gen;
END_RCPP
}
// idx2int
IntegerVector idx2int(IntegerVector idx, int len);
RcppExport SEXP _CasPhy_idx2int(SEXP idxSEXP, SEXP lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type len(lenSEXP);
    rcpp_result_gen = Rcpp::wrap(idx2int(idx, len));
    return rcpp_result_gen;
END_RCPP
}
// locusAND
IntegerVector locusAND(IntegerVector ve1, IntegerVector ve2);
RcppExport SEXP _CasPhy_locusAND(SEXP ve1SEXP, SEXP ve2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ve1(ve1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ve2(ve2SEXP);
    rcpp_result_gen = Rcpp::wrap(locusAND(ve1, ve2));
    return rcpp_result_gen;
END_RCPP
}
// locusXOR
IntegerVector locusXOR(IntegerVector ve1, IntegerVector ve2);
RcppExport SEXP _CasPhy_locusXOR(SEXP ve1SEXP, SEXP ve2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ve1(ve1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ve2(ve2SEXP);
    rcpp_result_gen = Rcpp::wrap(locusXOR(ve1, ve2));
    return rcpp_result_gen;
END_RCPP
}
// locusSUM
double locusSUM(IntegerVector ve, NumericVector weight);
RcppExport SEXP _CasPhy_locusSUM(SEXP veSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ve(veSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(locusSUM(ve, weight));
    return rcpp_result_gen;
END_RCPP
}
// locusSUMint
int locusSUMint(IntegerVector ve);
RcppExport SEXP _CasPhy_locusSUMint(SEXP veSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ve(veSEXP);
    rcpp_result_gen = Rcpp::wrap(locusSUMint(ve));
    return rcpp_result_gen;
END_RCPP
}
// reOrderEdge
IntegerMatrix reOrderEdge(IntegerMatrix edge, int root);
RcppExport SEXP _CasPhy_reOrderEdge(SEXP edgeSEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type root(rootSEXP);
    rcpp_result_gen = Rcpp::wrap(reOrderEdge(edge, root));
    return rcpp_result_gen;
END_RCPP
}
// charAncestral
IntegerVector charAncestral(IntegerMatrix mat);
RcppExport SEXP _CasPhy_charAncestral(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(charAncestral(mat));
    return rcpp_result_gen;
END_RCPP
}
// bitAncestral
IntegerVector bitAncestral(IntegerMatrix mat);
RcppExport SEXP _CasPhy_bitAncestral(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(bitAncestral(mat));
    return rcpp_result_gen;
END_RCPP
}
// greedyJoinEdge
IntegerMatrix greedyJoinEdge(IntegerMatrix mat, NumericMatrix weight, bool verbose);
RcppExport SEXP _CasPhy_greedyJoinEdge(SEXP matSEXP, SEXP weightSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(greedyJoinEdge(mat, weight, verbose));
    return rcpp_result_gen;
END_RCPP
}
// greedyJoinEdgeBit
IntegerMatrix greedyJoinEdgeBit(IntegerMatrix mat, NumericVector weight, bool verbose);
RcppExport SEXP _CasPhy_greedyJoinEdgeBit(SEXP matSEXP, SEXP weightSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(greedyJoinEdgeBit(mat, weight, verbose));
    return rcpp_result_gen;
END_RCPP
}
// collapseBranch
IntegerMatrix collapseBranch(IntegerMatrix edge, int ntip);
RcppExport SEXP _CasPhy_collapseBranch(SEXP edgeSEXP, SEXP ntipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type ntip(ntipSEXP);
    rcpp_result_gen = Rcpp::wrap(collapseBranch(edge, ntip));
    return rcpp_result_gen;
END_RCPP
}
// nodeKeep
IntegerVector nodeKeep(IntegerMatrix edge, int Ntip, IntegerMatrix node_mat, IntegerMatrix outmat, int keep_cutoff);
RcppExport SEXP _CasPhy_nodeKeep(SEXP edgeSEXP, SEXP NtipSEXP, SEXP node_matSEXP, SEXP outmatSEXP, SEXP keep_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type Ntip(NtipSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type node_mat(node_matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type outmat(outmatSEXP);
    Rcpp::traits::input_parameter< int >::type keep_cutoff(keep_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(nodeKeep(edge, Ntip, node_mat, outmat, keep_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// nodeKeepBit
IntegerVector nodeKeepBit(IntegerMatrix edge, int Ntip, IntegerMatrix node_mat, IntegerMatrix outmat, int keep_cutoff);
RcppExport SEXP _CasPhy_nodeKeepBit(SEXP edgeSEXP, SEXP NtipSEXP, SEXP node_matSEXP, SEXP outmatSEXP, SEXP keep_cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type Ntip(NtipSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type node_mat(node_matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type outmat(outmatSEXP);
    Rcpp::traits::input_parameter< int >::type keep_cutoff(keep_cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(nodeKeepBit(edge, Ntip, node_mat, outmat, keep_cutoff));
    return rcpp_result_gen;
END_RCPP
}
// imputeVector
IntegerVector imputeVector(IntegerVector ref, IntegerVector query);
RcppExport SEXP _CasPhy_imputeVector(SEXP refSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ref(refSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(imputeVector(ref, query));
    return rcpp_result_gen;
END_RCPP
}
// markDup
int markDup(int row_idx, IntegerMatrix mat);
RcppExport SEXP _CasPhy_markDup(SEXP row_idxSEXP, SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type row_idx(row_idxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(markDup(row_idx, mat));
    return rcpp_result_gen;
END_RCPP
}
// markDupBit
int markDupBit(int row_idx, IntegerMatrix mat);
RcppExport SEXP _CasPhy_markDupBit(SEXP row_idxSEXP, SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type row_idx(row_idxSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(markDupBit(row_idx, mat));
    return rcpp_result_gen;
END_RCPP
}
// edgeEvo
IntegerMatrix edgeEvo(IntegerMatrix edge, IntegerMatrix binary, int root);
RcppExport SEXP _CasPhy_edgeEvo(SEXP edgeSEXP, SEXP binarySEXP, SEXP rootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type binary(binarySEXP);
    Rcpp::traits::input_parameter< int >::type root(rootSEXP);
    rcpp_result_gen = Rcpp::wrap(edgeEvo(edge, binary, root));
    return rcpp_result_gen;
END_RCPP
}
// printB
void printB(int x);
RcppExport SEXP _CasPhy_printB(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    printB(x);
    return R_NilValue;
END_RCPP
}
// edge2vector
IntegerVector edge2vector(IntegerMatrix edge, int maxIdx);
RcppExport SEXP _CasPhy_edge2vector(SEXP edgeSEXP, SEXP maxIdxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type maxIdx(maxIdxSEXP);
    rcpp_result_gen = Rcpp::wrap(edge2vector(edge, maxIdx));
    return rcpp_result_gen;
END_RCPP
}
// findNeighborWeighted
IntegerMatrix findNeighborWeighted(IntegerMatrix mat, int maxChar, NumericVector weight, int n, double p, double radius, bool verbose);
RcppExport SEXP _CasPhy_findNeighborWeighted(SEXP matSEXP, SEXP maxCharSEXP, SEXP weightSEXP, SEXP nSEXP, SEXP pSEXP, SEXP radiusSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type maxChar(maxCharSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(findNeighborWeighted(mat, maxChar, weight, n, p, radius, verbose));
    return rcpp_result_gen;
END_RCPP
}
// findNeighborUnweighted
IntegerMatrix findNeighborUnweighted(IntegerMatrix mat, int maxChar, int n, double p, int radius, bool verbose);
RcppExport SEXP _CasPhy_findNeighborUnweighted(SEXP matSEXP, SEXP maxCharSEXP, SEXP nSEXP, SEXP pSEXP, SEXP radiusSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type maxChar(maxCharSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(findNeighborUnweighted(mat, maxChar, n, p, radius, verbose));
    return rcpp_result_gen;
END_RCPP
}
// findNeighborWeightedParallel
IntegerVector findNeighborWeightedParallel(int i, IntegerMatrix mat, int maxChar, NumericVector weight, int n, double p, double radius);
RcppExport SEXP _CasPhy_findNeighborWeightedParallel(SEXP iSEXP, SEXP matSEXP, SEXP maxCharSEXP, SEXP weightSEXP, SEXP nSEXP, SEXP pSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type maxChar(maxCharSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(findNeighborWeightedParallel(i, mat, maxChar, weight, n, p, radius));
    return rcpp_result_gen;
END_RCPP
}
// findNeighborUnweightedParallel
IntegerVector findNeighborUnweightedParallel(int i, IntegerMatrix mat, int maxChar, int n, double p, int radius);
RcppExport SEXP _CasPhy_findNeighborUnweightedParallel(SEXP iSEXP, SEXP matSEXP, SEXP maxCharSEXP, SEXP nSEXP, SEXP pSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type maxChar(maxCharSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(findNeighborUnweightedParallel(i, mat, maxChar, n, p, radius));
    return rcpp_result_gen;
END_RCPP
}
// tipMergeNeighbor
IntegerVector tipMergeNeighbor(IntegerMatrix mat, double p, bool sqrt_nNeighbor, int min_shared, bool verbose);
RcppExport SEXP _CasPhy_tipMergeNeighbor(SEXP matSEXP, SEXP pSEXP, SEXP sqrt_nNeighborSEXP, SEXP min_sharedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type sqrt_nNeighbor(sqrt_nNeighborSEXP);
    Rcpp::traits::input_parameter< int >::type min_shared(min_sharedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(tipMergeNeighbor(mat, p, sqrt_nNeighbor, min_shared, verbose));
    return rcpp_result_gen;
END_RCPP
}
// tipMergeNeighborBig
IntegerVector tipMergeNeighborBig(SEXP pNeighborMat, IntegerVector nNeighbor, double p, bool sqrt_nNeighbor, int min_shared, bool verbose);
RcppExport SEXP _CasPhy_tipMergeNeighborBig(SEXP pNeighborMatSEXP, SEXP nNeighborSEXP, SEXP pSEXP, SEXP sqrt_nNeighborSEXP, SEXP min_sharedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pNeighborMat(pNeighborMatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nNeighbor(nNeighborSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type sqrt_nNeighbor(sqrt_nNeighborSEXP);
    Rcpp::traits::input_parameter< int >::type min_shared(min_sharedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(tipMergeNeighborBig(pNeighborMat, nNeighbor, p, sqrt_nNeighbor, min_shared, verbose));
    return rcpp_result_gen;
END_RCPP
}
// nodeDes
IntegerMatrix nodeDes(IntegerMatrix edge, int nnode, int ntip);
RcppExport SEXP _CasPhy_nodeDes(SEXP edgeSEXP, SEXP nnodeSEXP, SEXP ntipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type nnode(nnodeSEXP);
    Rcpp::traits::input_parameter< int >::type ntip(ntipSEXP);
    rcpp_result_gen = Rcpp::wrap(nodeDes(edge, nnode, ntip));
    return rcpp_result_gen;
END_RCPP
}
// nodeDesBig
void nodeDesBig(IntegerMatrix edge, int nnode, int ntip, std::string file_path, int cacheSize);
RcppExport SEXP _CasPhy_nodeDesBig(SEXP edgeSEXP, SEXP nnodeSEXP, SEXP ntipSEXP, SEXP file_pathSEXP, SEXP cacheSizeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< int >::type nnode(nnodeSEXP);
    Rcpp::traits::input_parameter< int >::type ntip(ntipSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_path(file_pathSEXP);
    Rcpp::traits::input_parameter< int >::type cacheSize(cacheSizeSEXP);
    nodeDesBig(edge, nnode, ntip, file_path, cacheSize);
    return R_NilValue;
END_RCPP
}
// findNeighborRangeUnweighted
IntegerVector findNeighborRangeUnweighted(int i, IntegerMatrix mat, int maxChar, IntegerMatrix range, int offset, int n, double p, int radius);
RcppExport SEXP _CasPhy_findNeighborRangeUnweighted(SEXP iSEXP, SEXP matSEXP, SEXP maxCharSEXP, SEXP rangeSEXP, SEXP offsetSEXP, SEXP nSEXP, SEXP pSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type maxChar(maxCharSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< int >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(findNeighborRangeUnweighted(i, mat, maxChar, range, offset, n, p, radius));
    return rcpp_result_gen;
END_RCPP
}
// findNeighborRangeWeighted
IntegerVector findNeighborRangeWeighted(int i, IntegerMatrix mat, int maxChar, IntegerMatrix range, int offset, NumericVector weight, int n, double p, double radius);
RcppExport SEXP _CasPhy_findNeighborRangeWeighted(SEXP iSEXP, SEXP matSEXP, SEXP maxCharSEXP, SEXP rangeSEXP, SEXP offsetSEXP, SEXP weightSEXP, SEXP nSEXP, SEXP pSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type maxChar(maxCharSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< int >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(findNeighborRangeWeighted(i, mat, maxChar, range, offset, weight, n, p, radius));
    return rcpp_result_gen;
END_RCPP
}
// imputeMat
IntegerVector imputeMat(int i, IntegerMatrix mat, IntegerMatrix neighbor_mat, int offset);
RcppExport SEXP _CasPhy_imputeMat(SEXP iSEXP, SEXP matSEXP, SEXP neighbor_matSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type neighbor_mat(neighbor_matSEXP);
    Rcpp::traits::input_parameter< int >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(imputeMat(i, mat, neighbor_mat, offset));
    return rcpp_result_gen;
END_RCPP
}
// greedyJoinEdgeBig
IntegerMatrix greedyJoinEdgeBig(IntegerMatrix mat, NumericMatrix weight, SEXP pShared, bool verbose);
RcppExport SEXP _CasPhy_greedyJoinEdgeBig(SEXP matSEXP, SEXP weightSEXP, SEXP pSharedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pShared(pSharedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(greedyJoinEdgeBig(mat, weight, pShared, verbose));
    return rcpp_result_gen;
END_RCPP
}
// greedyJoinEdgeBitBig
IntegerMatrix greedyJoinEdgeBitBig(IntegerMatrix mat, NumericVector weight, SEXP pShared, bool verbose);
RcppExport SEXP _CasPhy_greedyJoinEdgeBitBig(SEXP matSEXP, SEXP weightSEXP, SEXP pSharedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< SEXP >::type pShared(pSharedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(greedyJoinEdgeBitBig(mat, weight, pShared, verbose));
    return rcpp_result_gen;
END_RCPP
}
// radiusUnweightedParallel
IntegerVector radiusUnweightedParallel(int i, IntegerMatrix mat, int maxChar, int radius);
RcppExport SEXP _CasPhy_radiusUnweightedParallel(SEXP iSEXP, SEXP matSEXP, SEXP maxCharSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type maxChar(maxCharSEXP);
    Rcpp::traits::input_parameter< int >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(radiusUnweightedParallel(i, mat, maxChar, radius));
    return rcpp_result_gen;
END_RCPP
}
// radiusWeightedParallel
IntegerVector radiusWeightedParallel(int i, IntegerMatrix mat, int maxChar, NumericVector weight, double radius);
RcppExport SEXP _CasPhy_radiusWeightedParallel(SEXP iSEXP, SEXP matSEXP, SEXP maxCharSEXP, SEXP weightSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type maxChar(maxCharSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(radiusWeightedParallel(i, mat, maxChar, weight, radius));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CasPhy_mutationNested", (DL_FUNC) &_CasPhy_mutationNested, 2},
    {"_CasPhy_mutationNestedBit", (DL_FUNC) &_CasPhy_mutationNestedBit, 2},
    {"_CasPhy_transitionRoot", (DL_FUNC) &_CasPhy_transitionRoot, 2},
    {"_CasPhy_matCoding", (DL_FUNC) &_CasPhy_matCoding, 2},
    {"_CasPhy_int2binary", (DL_FUNC) &_CasPhy_int2binary, 2},
    {"_CasPhy_int2idx", (DL_FUNC) &_CasPhy_int2idx, 1},
    {"_CasPhy_idx2int", (DL_FUNC) &_CasPhy_idx2int, 2},
    {"_CasPhy_locusAND", (DL_FUNC) &_CasPhy_locusAND, 2},
    {"_CasPhy_locusXOR", (DL_FUNC) &_CasPhy_locusXOR, 2},
    {"_CasPhy_locusSUM", (DL_FUNC) &_CasPhy_locusSUM, 2},
    {"_CasPhy_locusSUMint", (DL_FUNC) &_CasPhy_locusSUMint, 1},
    {"_CasPhy_reOrderEdge", (DL_FUNC) &_CasPhy_reOrderEdge, 2},
    {"_CasPhy_charAncestral", (DL_FUNC) &_CasPhy_charAncestral, 1},
    {"_CasPhy_bitAncestral", (DL_FUNC) &_CasPhy_bitAncestral, 1},
    {"_CasPhy_greedyJoinEdge", (DL_FUNC) &_CasPhy_greedyJoinEdge, 3},
    {"_CasPhy_greedyJoinEdgeBit", (DL_FUNC) &_CasPhy_greedyJoinEdgeBit, 3},
    {"_CasPhy_collapseBranch", (DL_FUNC) &_CasPhy_collapseBranch, 2},
    {"_CasPhy_nodeKeep", (DL_FUNC) &_CasPhy_nodeKeep, 5},
    {"_CasPhy_nodeKeepBit", (DL_FUNC) &_CasPhy_nodeKeepBit, 5},
    {"_CasPhy_imputeVector", (DL_FUNC) &_CasPhy_imputeVector, 2},
    {"_CasPhy_markDup", (DL_FUNC) &_CasPhy_markDup, 2},
    {"_CasPhy_markDupBit", (DL_FUNC) &_CasPhy_markDupBit, 2},
    {"_CasPhy_edgeEvo", (DL_FUNC) &_CasPhy_edgeEvo, 3},
    {"_CasPhy_printB", (DL_FUNC) &_CasPhy_printB, 1},
    {"_CasPhy_edge2vector", (DL_FUNC) &_CasPhy_edge2vector, 2},
    {"_CasPhy_findNeighborWeighted", (DL_FUNC) &_CasPhy_findNeighborWeighted, 7},
    {"_CasPhy_findNeighborUnweighted", (DL_FUNC) &_CasPhy_findNeighborUnweighted, 6},
    {"_CasPhy_findNeighborWeightedParallel", (DL_FUNC) &_CasPhy_findNeighborWeightedParallel, 7},
    {"_CasPhy_findNeighborUnweightedParallel", (DL_FUNC) &_CasPhy_findNeighborUnweightedParallel, 6},
    {"_CasPhy_tipMergeNeighbor", (DL_FUNC) &_CasPhy_tipMergeNeighbor, 5},
    {"_CasPhy_tipMergeNeighborBig", (DL_FUNC) &_CasPhy_tipMergeNeighborBig, 6},
    {"_CasPhy_nodeDes", (DL_FUNC) &_CasPhy_nodeDes, 3},
    {"_CasPhy_nodeDesBig", (DL_FUNC) &_CasPhy_nodeDesBig, 5},
    {"_CasPhy_findNeighborRangeUnweighted", (DL_FUNC) &_CasPhy_findNeighborRangeUnweighted, 8},
    {"_CasPhy_findNeighborRangeWeighted", (DL_FUNC) &_CasPhy_findNeighborRangeWeighted, 9},
    {"_CasPhy_imputeMat", (DL_FUNC) &_CasPhy_imputeMat, 4},
    {"_CasPhy_greedyJoinEdgeBig", (DL_FUNC) &_CasPhy_greedyJoinEdgeBig, 4},
    {"_CasPhy_greedyJoinEdgeBitBig", (DL_FUNC) &_CasPhy_greedyJoinEdgeBitBig, 4},
    {"_CasPhy_radiusUnweightedParallel", (DL_FUNC) &_CasPhy_radiusUnweightedParallel, 4},
    {"_CasPhy_radiusWeightedParallel", (DL_FUNC) &_CasPhy_radiusWeightedParallel, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_CasPhy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
