# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mutationNested <- function(des, ans) {
    .Call(`_CasPhy_mutationNested`, des, ans)
}

mutationNestedBit <- function(des, ans) {
    .Call(`_CasPhy_mutationNestedBit`, des, ans)
}

transitionRoot <- function(transition, idx) {
    .Call(`_CasPhy_transitionRoot`, transition, idx)
}

matCoding <- function(mat, loci) {
    .Call(`_CasPhy_matCoding`, mat, loci)
}

int2binary <- function(ve, output_len = 0L) {
    .Call(`_CasPhy_int2binary`, ve, output_len)
}

int2idx <- function(ve) {
    .Call(`_CasPhy_int2idx`, ve)
}

idx2int <- function(idx, len) {
    .Call(`_CasPhy_idx2int`, idx, len)
}

locusAND <- function(ve1, ve2) {
    .Call(`_CasPhy_locusAND`, ve1, ve2)
}

locusXOR <- function(ve1, ve2) {
    .Call(`_CasPhy_locusXOR`, ve1, ve2)
}

locusSUM <- function(ve, weight) {
    .Call(`_CasPhy_locusSUM`, ve, weight)
}

locusSUMint <- function(ve) {
    .Call(`_CasPhy_locusSUMint`, ve)
}

reOrderEdge <- function(edge, root) {
    .Call(`_CasPhy_reOrderEdge`, edge, root)
}

charAncestral <- function(mat) {
    .Call(`_CasPhy_charAncestral`, mat)
}

bitAncestral <- function(mat) {
    .Call(`_CasPhy_bitAncestral`, mat)
}

greedyJoinEdge <- function(mat, weight, verbose = FALSE) {
    .Call(`_CasPhy_greedyJoinEdge`, mat, weight, verbose)
}

greedyJoinEdgeBit <- function(mat, weight, verbose = FALSE) {
    .Call(`_CasPhy_greedyJoinEdgeBit`, mat, weight, verbose)
}

collapseBranch <- function(edge, ntip) {
    .Call(`_CasPhy_collapseBranch`, edge, ntip)
}

nodeKeep <- function(edge, Ntip, node_mat, outmat, keep_cutoff) {
    .Call(`_CasPhy_nodeKeep`, edge, Ntip, node_mat, outmat, keep_cutoff)
}

nodeKeepBit <- function(edge, Ntip, node_mat, outmat, keep_cutoff) {
    .Call(`_CasPhy_nodeKeepBit`, edge, Ntip, node_mat, outmat, keep_cutoff)
}

imputeVector <- function(ref, query) {
    .Call(`_CasPhy_imputeVector`, ref, query)
}

markDup <- function(row_idx, mat) {
    .Call(`_CasPhy_markDup`, row_idx, mat)
}

markDupBit <- function(row_idx, mat) {
    .Call(`_CasPhy_markDupBit`, row_idx, mat)
}

edgeEvo <- function(edge, binary, root) {
    .Call(`_CasPhy_edgeEvo`, edge, binary, root)
}

printB <- function(x) {
    invisible(.Call(`_CasPhy_printB`, x))
}

edge2vector <- function(edge, maxIdx) {
    .Call(`_CasPhy_edge2vector`, edge, maxIdx)
}

findNeighborWeighted <- function(mat, maxChar, weight, n = 10L, p = 0.5, radius = 0, verbose = FALSE) {
    .Call(`_CasPhy_findNeighborWeighted`, mat, maxChar, weight, n, p, radius, verbose)
}

findNeighborUnweighted <- function(mat, maxChar, n = 10L, p = 0.5, radius = 0L, verbose = FALSE) {
    .Call(`_CasPhy_findNeighborUnweighted`, mat, maxChar, n, p, radius, verbose)
}

findNeighborWeightedParallel <- function(i, mat, maxChar, weight, n = 10L, p = 0.5, radius = 0) {
    .Call(`_CasPhy_findNeighborWeightedParallel`, i, mat, maxChar, weight, n, p, radius)
}

findNeighborUnweightedParallel <- function(i, mat, maxChar, n = 10L, p = 0.5, radius = 0L) {
    .Call(`_CasPhy_findNeighborUnweightedParallel`, i, mat, maxChar, n, p, radius)
}

tipMergeNeighbor <- function(mat, p = 0.8, sqrt_nNeighbor = FALSE, min_shared = 0L, verbose = FALSE) {
    .Call(`_CasPhy_tipMergeNeighbor`, mat, p, sqrt_nNeighbor, min_shared, verbose)
}

tipMergeNeighborBig <- function(pNeighborMat, nNeighbor, p = 0.8, sqrt_nNeighbor = FALSE, min_shared = 0L, verbose = FALSE) {
    .Call(`_CasPhy_tipMergeNeighborBig`, pNeighborMat, nNeighbor, p, sqrt_nNeighbor, min_shared, verbose)
}

nodeDes <- function(edge, nnode, ntip) {
    .Call(`_CasPhy_nodeDes`, edge, nnode, ntip)
}

nodeDesBig <- function(edge, nnode, ntip, file_path, cacheSize = 8192L) {
    invisible(.Call(`_CasPhy_nodeDesBig`, edge, nnode, ntip, file_path, cacheSize))
}

findNeighborRangeUnweighted <- function(i, mat, maxChar, range, offset, n = 10L, p = 0.5, radius = 0L) {
    .Call(`_CasPhy_findNeighborRangeUnweighted`, i, mat, maxChar, range, offset, n, p, radius)
}

findNeighborRangeWeighted <- function(i, mat, maxChar, range, offset, weight, n = 10L, p = 0.5, radius = 0) {
    .Call(`_CasPhy_findNeighborRangeWeighted`, i, mat, maxChar, range, offset, weight, n, p, radius)
}

imputeMat <- function(i, mat, neighbor_mat, offset) {
    .Call(`_CasPhy_imputeMat`, i, mat, neighbor_mat, offset)
}

greedyJoinEdgeBig <- function(mat, weight, pShared, verbose = FALSE) {
    .Call(`_CasPhy_greedyJoinEdgeBig`, mat, weight, pShared, verbose)
}

greedyJoinEdgeBitBig <- function(mat, weight, pShared, verbose = FALSE) {
    .Call(`_CasPhy_greedyJoinEdgeBitBig`, mat, weight, pShared, verbose)
}

radiusUnweightedParallel <- function(i, mat, maxChar, radius) {
    .Call(`_CasPhy_radiusUnweightedParallel`, i, mat, maxChar, radius)
}

radiusWeightedParallel <- function(i, mat, maxChar, weight, radius) {
    .Call(`_CasPhy_radiusWeightedParallel`, i, mat, maxChar, weight, radius)
}

